### PR TITLE
Fix error message and default merge tolerance

### LINKED ISSUE #397: With m_mergetolerance now being used in the Adapter, a default value should be set
#### Description:

If a `LusasSettings` object is not created, the `m_mergeTolerance` is left as `NaN` which causes a crash.

#### Steps to reproduce:

1. Push `Panel`s with `Openings` without using a `LusasSettings` object

#### Expected behaviour:

Default value of 1E-6 (default value in Lusas) to be used.

### LINKED ISSUE #398: Error message for pushing Panels with openings has -1 for id (error message is intentional)
#### Description:

If you try to push panels with invalid openings, the error message returns -1 instead of useful information.

#### Steps to reproduce:

See test script.

#### Expected behaviour:

Ids should match ids from Lusas.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Lusas_Toolkit/%23396-AddSupportForPanelWithOpenings?csf=1&web=1&e=gfan72

### PR DESCRIPTION
**Pull request by KalleEdstroem**
### Issues addressed by this PR

Closes #397 
Closes #398 

Fixed two bug related to Panel with openings. Giving m_mergeTolerance a default value and correcting Ids in Error message.

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Lusas_Toolkit/%23396-AddSupportForPanelWithOpenings?csf=1&web=1&e=uOsKNh

### Changelog

- Added default value for `m_mergeTolerance` to be `Tolerance.Distance` (1E-6).
- Changed Ids in Error message regarding invalid `Openings` in `Create`/`Surface.cs`

### CODE REVIEW

**Comment by KalleEdstroem** [comment]
You still get a `-1` back for ID of the Opening that never gets created since its `Edges` defining it is not Planar.

File: Lusas_Adapter/CRUD/Create/Elements/Surface.cs [hunk 1]
```diff
@@ -81,21 +81,21 @@ private IFSurface CreateSurface(Panel panel)
...
-                    Engine.Base.Compute.RecordError($"Could not find the ids for at least one of the Openings on Surface {GetAdapterId<string>(panel)}, Opening not created.");
+                    Engine.Base.Compute.RecordError($"Could not find the ids for at least one of the Openings on Surface {lusasSurface.getID()}, Opening not created.");
                     continue;
                 }
 
 
                 if (EdgeIntersection(opening.Edges, panel.ExternalEdges))
                 {
-                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {GetAdapterId<string>(panel)} intersects with at least one Edge defining the Opening {GetAdapterId<string>(opening)}, Opening not created.");
+                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {lusasSurface.getID()} intersects with at least one Edge defining the Opening {openingID}, Opening not created.");
```
Comment (peterjamesnugent) [inline Lusas_Adapter/CRUD/Create/Elements/Surface.cs:91]:
```suggestion
                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {lusasSurface.getID()} intersects with at least one Edge defining the Opening, Opening not created.");
```

File: Lusas_Adapter/CRUD/Create/Elements/Surface.cs [hunk 2]
```diff
@@ -81,21 +81,21 @@ private IFSurface CreateSurface(Panel panel)
...
                     continue;
                 }
                    
 
                 if (!Engine.Geometry.Query.IsCoplanar(opening.FitPlane(), panel.FitPlane(), m_mergeTolerance))
                 {
-                    Engine.Base.Compute.RecordError($"The geometry defining the Panel {GetAdapterId<string>(panel)} is not Coplanar the Opening {GetAdapterId<string>(opening)}, Opening not created.");
+                    Engine.Base.Compute.RecordError($"The geometry defining the Panel {lusasSurface.getID()} is not Coplanar with the Opening {openingID}, Opening not created.");
```
Comment (peterjamesnugent) [inline Lusas_Adapter/CRUD/Create/Elements/Surface.cs:98]:
```suggestion
                    Engine.Base.Compute.RecordError($"The geometry defining the Panel {lusasSurface.getID()} is not Coplanar with the Opening, Opening not created.");
```

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
Thanks @KalleEdstroem, where the `Opening` does not get created, I do not think including the `-1` is useful.

Can we also add an `else` statement here:
https://github.com/BHoM/Lusas_Toolkit/blob/ef9ff1dd2dfccfd043c01fb2a5986acd91e347dc/Lusas_Adapter/LusasAdapter.cs#L174-L178

You could have a scenario where the user has a model with a tolerance of `1E-3`, and then the Adapter in the background is set to `1E-6`. Within the `else` statement we should add a warning saying a merge tolerance has not been set and has defaulted to 1E-6.

File: Lusas_Adapter/CRUD/Create/Elements/Surface.cs (hunk 1 above)
Comment (KalleEdstroem) [reply Lusas_Adapter/CRUD/Create/Elements/Surface.cs]: Yes, agree that it is not necessary.

File: Lusas_Adapter/CRUD/Create/Elements/Surface.cs (hunk 2 above)
Comment (KalleEdstroem) [reply Lusas_Adapter/CRUD/Create/Elements/Surface.cs]: Agree, same as above.

File: Lusas_Adapter/CRUD/Create/Elements/Surface.cs [hunk 3]
```diff
@@ -81,21 +81,21 @@ private IFSurface CreateSurface(Panel panel)
...
-                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {GetAdapterId<string>(panel)} intersects with at least one Edge defining the Opening {GetAdapterId<string>(opening)}, Opening not created.");
+                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {lusasSurface.getID()} intersects with at least one Edge defining the Opening, Opening not created.");
                     continue;
                 }
                    
 
                 if (!Engine.Geometry.Query.IsCoplanar(opening.FitPlane(), panel.FitPlane(), m_mergeTolerance))
                 {
-                    Engine.Base.Compute.RecordError($"The geometry defining the Panel {GetAdapterId<string>(panel)} is not Coplanar the Opening {GetAdapterId<string>(opening)}, Opening not created.");
+                    Engine.Base.Compute.RecordError($"The geometry defining the Panel {lusasSurface.getID()} is not Coplanar with the Opening, Opening not created.");
```
Comment (peterjamesnugent) [inline Lusas_Adapter/CRUD/Create/Elements/Surface.cs:98]:
```suggestion
                    Engine.Base.Compute.RecordError($"The geometry defining Panel {lusasSurface.getID()} is not Coplanar with an Opening, this Opening has not been created.");
```

File: Lusas_Adapter/CRUD/Create/Elements/Surface.cs [hunk 4]
```diff
@@ -81,21 +81,21 @@ private IFSurface CreateSurface(Panel panel)
...
-                    Engine.Base.Compute.RecordError($"Could not find the ids for at least one of the Openings on Surface {GetAdapterId<string>(panel)}, Opening not created.");
+                    Engine.Base.Compute.RecordError($"Could not find the ids for at least one of the Openings on Surface {lusasSurface.getID()}, Opening not created.");
                     continue;
                 }
 
 
                 if (EdgeIntersection(opening.Edges, panel.ExternalEdges))
                 {
-                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {GetAdapterId<string>(panel)} intersects with at least one Edge defining the Opening {GetAdapterId<string>(opening)}, Opening not created.");
+                    Engine.Base.Compute.RecordError($"At least one Edge defining the Panel {lusasSurface.getID()} intersects with at least one Edge defining the Opening, Opening not created.");
```
Comment (peterjamesnugent) [inline Lusas_Adapter/CRUD/Create/Elements/Surface.cs:91]:
```suggestion
                    Engine.Base.Compute.RecordError($"At least one Edge defining Panel {lusasSurface.getID()} intersects with at least one Edge defining an Opening, this Opening has not been created.");
```

File: Lusas_Adapter/CRUD/Create/Elements/Surface.cs [hunk 5]
```diff
@@ -81,21 +81,21 @@ private IFSurface CreateSurface(Panel panel)
 
                 if (string.IsNullOrEmpty(openingID))
                 {
-                    Engine.Base.Compute.RecordError($"Could not find the ids for at least one of the Openings on Surface {GetAdapterId<string>(panel)}, Opening not created.");
+                    Engine.Base.Compute.RecordError($"Could not find the ids for at least one of the Openings on Surface {lusasSurface.getID()}, Opening not created.");
```
Comment (peterjamesnugent) [inline Lusas_Adapter/CRUD/Create/Elements/Surface.cs:84]:
```suggestion
                    Engine.Base.Compute.RecordError($"Could not find the ids for at least one of the Openings on Panel {lusasSurface.getID()}, this Opening has not been created.");
```

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
I have tested using the scripts, have with the warning on the Adapter, just some minor changes for the `Panel` warnings.

**Review by peterjamesnugent — APPROVED** [review]
Functionality has not changed, just the contents of the warning messages. Happy all my comments have been addressed.

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge
